apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: publish-release
  annotations:
    chains.tekton.dev/transparency-upload: "true"
spec:
  params:
    - name: package
      description: package to release (e.g. github.com/<org>/<project>)
      default: github.com/tektoncd/pipeline

    - name: images
      description: List of cmd/* paths to be published as images
      default: "controller webhook entrypoint nop workingdirinit resolvers sidecarlogresults events"

    - name: koExtraArgs
      description: Extra args to be passed to ko
      default: "--preserve-import-paths"

    - name: versionTag
      description: The version, vX.Y.Z for stable or vYYYYMMDD-abc1234 for nightly.

    - name: imageRegistry
      description: The target image registry
      default: na.artifactory.swg-devops.com # 

    - name: imageRegistryPath
      description: The path (project) in the image registry
      default: sys-linux-power-team-ftp3distro-docker-images-docker-local/tekton #

    - name: imageRegistryRegions
      description: The target image registry regions
      default: ""

    - name: imageRegistryUser
      description: Username to be used to login to the container registry
      default: "_json_key"

    - name: releaseAsLatest
      description: Whether to tag and publish this release as Pipelines latest
      default: "true"

    - name: platforms
      description: Platforms to publish for (e.g. linux/amd64,linux/arm64)
      default: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le,windows/amd64

    - name: serviceAccountPath
      description: Service account path within the release-secret workspace

  workspaces:
    - name: source
      description: Workspace containing the repo.
      mountPath: /go/src/github.com/tektoncd/pipeline

    - name: release-secret
      description: Secret with credentials to push to registry and output bucket

    - name: output
      description: Workspace where release YAML will be written

  stepTemplate:
    env:
      - name: PROJECT_ROOT
        value: "$(workspaces.source.path)"
      - name: CONTAINER_REGISTRY
        value: "$(params.imageRegistry)/$(params.imageRegistryPath)"
      - name: IMAGE_REGISTRY_PATH
        value: "$(params.imageRegistryPath)"
      - name: CONTAINER_REGISTRY_USER
        value: "$(params.imageRegistryUser)"
      - name: REGIONS
        value: "$(params.imageRegistryRegions)"
      - name: OUTPUT_RELEASE_DIR
        value: "$(workspaces.output.path)/$(params.versionTag)"
      - name: KO_EXTRA_ARGS
        value: "$(params.koExtraArgs)"

  results:
    - name: IMAGES

  steps:

  - name: container-registry-auth
    image: cgr.dev/chainguard/crane:latest-dev
    script: |
      #!/bin/sh
      set -ex
      # Login to the container registry
      echo "Authenticating to $(params.imageRegistry)"
      DOCKER_CONFIG=$(cat $(workspaces.release-secret.path)/$(params.serviceAccountPath) | \
        crane auth login -u $(params.imageRegistryUser) --password-stdin $(params.imageRegistry))
      cp ${DOCKER_CONFIG} /workspace/docker-config.json

  - name: create-ko-yaml
    image: cgr.dev/chainguard/go:latest-dev
    script: |
      #!/bin/sh
      set -ex
      mkdir -p ~/.docker
      cp /workspace/docker-config.json ~/.docker/config.json

      cd ${PROJECT_ROOT}
      cp ${PROJECT_ROOT}/.ko.yaml /workspace/.ko.yaml

      echo "Configured .ko.yaml for $(params.imageRegistry)/$(params.imageRegistryPath)"
      cat /workspace/.ko.yaml

  - name: run-ko
    image: ghcr.io/tektoncd/plumbing/ko@sha256:990ec7fc709567e0d26fa40788a040b97598343d2fcb7252751316e34f31c4cc
    env:
      - name: KO_DOCKER_REPO
        value: $(params.imageRegistry)/$(params.imageRegistryPath)
      - name: DOCKER_CONFIG
        value: /tekton/home/.docker
      - name: GOFLAGS
        value: "-mod=vendor"
    script: |
      #!/usr/bin/env sh
      set -ex
      echo "Running ko publish for $(params.imageRegistry)/$(params.imageRegistryPath)"
      git config --global --add safe.directory ${PROJECT_ROOT}
      export KO_CONFIG_PATH=/workspace
      mkdir -p ~/.docker
      cp /workspace/docker-config.json ~/.docker/config.json

      cd ${PROJECT_ROOT}
      git tag $(params.versionTag)

      ko resolve \
        --image-label=org.opencontainers.image.source=https://$(params.package) \
        --platform=$(params.platforms) \
        -t $(params.versionTag) \
        -R ${KO_EXTRA_ARGS} \
        -f ${PROJECT_ROOT}/config/ > $OUTPUT_RELEASE_DIR/release.yaml

  - name: koparse
    image: ghcr.io/tektoncd/plumbing/koparse:latest
    script: |
      set -ex
      echo "Parsing built images from release.yaml"
      for cmd in $(params.images); do
        IMAGES="${IMAGES} $(params.package)/cmd/${cmd}:$(params.versionTag)"
      done
      koparse \
        --path $OUTPUT_RELEASE_DIR/release.yaml \
        --base $(params.package) \
        --container-registry ${CONTAINER_REGISTRY} \
        --images ${IMAGES} > /workspace/built_images

  - name: tag-images
    image: cgr.dev/chainguard/crane:latest-dev
    script: |
      #!/bin/sh
      set -ex
      mkdir -p ~/.docker
      cp /workspace/docker-config.json ~/.docker/config.json
      for IMAGE in $(cat /workspace/built_images); do
        IMAGE_WITHOUT_SHA=${IMAGE%%@*}
        crane cp ${IMAGE} ${IMAGE_WITHOUT_SHA}:latest
      done
